name: gopass
base: core20 # the base snap is the execution environment for this snap
version: '1.12.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: The team password manager
description: |
  Gopass is a team password manager

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
license: MIT

apps:
  gopass:
    environment:
      GNUPGHOME: $SNAP_REAL_HOME/.gnupg
      XDG_CONFIG_HOME: $SNAP_REAL_HOME/.config
      XDG_CACHE_HOME: $SNAP_REAL_HOME/.cache
      XDG_DATA_HOME: $SNAP_REAL_HOME/.local/share
    plugs: ["klipper-svc", "home", "network", "personal-files", "gpg-keys", "ssh-keys", "x11"]
    command: bin/gopass
  gopass-jsonapi:
    environment:
      GNUPGHOME: $SNAP_REAL_HOME/.gnupg
      XDG_CONFIG_HOME: $SNAP_REAL_HOME/.config
      XDG_CACHE_HOME: $SNAP_REAL_HOME/.cache
      XDG_DATA_HOME: $SNAP_REAL_HOME/.local/share
    plugs: ["klipper-svc", "home", "network", "personal-files", "gpg-keys", "ssh-keys", "x11"]
    command: bin/gopass-jsonapi

plugs:
  home:
  personal-files:
    write:
    - $HOME/.config/gopass
    - $HOME/.local/share/gopass
  klipper-svc:
    bus: session
    interface: dbus
    name: org.kde.klipper

parts:
  gopass:
    plugin: make
    source: https://github.com/gopasspw/gopass.git
    source-type: git
    source-commit: v1.12.6-rc0
    build-snaps:
      - go/1.16/stable
    build-packages:
      - git
      - gpg
    stage-packages:
      - git
      - gnupg
      - xclip
      - ssh
      - pinentry
  gopass-jsonapi:
    plugin: make
    source: https://github.com/gopasspw/gopass-jsonapi.git
    source-type: git
    source-commit: v1.11.1
    build-snaps:
      - go/1.16/stable
    build-packages:
      - git
      - gpg
    stage-packages:
      - git
      - gnupg
      - xclip
      - ssh
      - pinentry
